# Generated by Django 6.0.6 on 2026-06-16 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('user_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='会員ID')),
                ('password', models.CharField(max_length=255, verbose_name='パスワード')),
                ('name', models.CharField(max_length=126, verbose_name='名前')),
                ('address', models.CharField(max_length=256, verbose_name='住所')),
            ],
            options={
                'db_table': 'account_user',
            },
        ),
        migrations.CreateModel(
            name='AdministratorAdmin',
            fields=[
                ('admin_id', models.CharField(max_length=123, primary_key=True, serialize=False, verbose_name='管理者ID')),
                ('password', models.CharField(max_length=256, verbose_name='パスワード')),
            ],
            options={
                'db_table': 'administrator_admin',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='カテゴリID')),
                ('name', models.CharField(max_length=256, verbose_name='カテゴリ名')),
            ],
            options={
                'db_table': 'shopping_category',
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品名')),
                ('manufacture', models.CharField(max_length=32, verbose_name='メーカ名')),
                ('color', models.CharField(max_length=16, verbose_name='商品の色')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('stock', models.IntegerField(verbose_name='在庫数')),
                ('recommend', models.BooleanField(default=False, verbose_name='オススメ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop01.shoppingcategory', verbose_name='カテゴリID')),
            ],
            options={
                'db_table': 'shopping_item',
            },
        ),
        migrations.CreateModel(
            name='ShoppingItemincart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('booked_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop01.shoppingitem', verbose_name='商品ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop01.accountuser', verbose_name='会員ID')),
            ],
            options={
                'db_table': 'shopping_itemincart',
            },
        ),
        migrations.CreateModel(
            name='ShoppingPurchase',
            fields=[
                ('purchase_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='注文ID')),
                ('destination', models.CharField(max_length=256, verbose_name='配送先')),
                ('booked_date', models.DateTimeField(verbose_name='注文日')),
                ('cancel', models.BooleanField(default=False, verbose_name='キャンセル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop01.accountuser', verbose_name='注文者')),
            ],
            options={
                'db_table': 'shopping_purchase',
            },
        ),
        migrations.CreateModel(
            name='ShoppingPurchasedetail',
            fields=[
                ('purchase_detail_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='注文者詳細ID')),
                ('amount', models.IntegerField(verbose_name='注文数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop01.shoppingitem', verbose_name='商品ID')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop01.shoppingpurchase', verbose_name='注文ID')),
            ],
            options={
                'db_table': 'shopping_purchasedetail',
            },
        ),
    ]
