# Generated by Django 5.1 on 2026-06-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingpurchase',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoppingpurchase',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
