# Generated by Django 5.1 on 2026-06-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='商品画像'),
        ),
    ]
