# Generated by Django 5.1 on 2026-06-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop01', '0002_shoppingpurchase_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingpurchase',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='shoppingpurchase',
            name='total_price',
        ),
        migrations.AddField(
            model_name='shoppingpurchasedetail',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoppingpurchasedetail',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
