# Generated by Django 6.0.6 on 2026-06-18 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop01', '0002_shoppingitem_image'),
        ('shop01', '0004_remove_shoppingpurchasedetail_discount_and_more'),
    ]

    operations = [
    ]
